[package]
name = "embassy-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_cell = { version = "1.1", features = ["nightly"] }
embedded-io-async = { version = "0.6.1" }
heapless = "0.7.16"

defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }
cortex-m = { version = "0.7.6", features = [
  "inline-asm",
  "critical-section-single-core",
], optional = true }
cortex-m-rt = { version = "0.7.0", optional = true }
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }
async-io = { version = "1.6.0", optional = true }
ringbuf = { version = "0.3.3", default-features = false }

# embedded-hal-async = "1.0.0-rc.3"
# embedded-hal-nb = "1.0.0-rc.3"
# embedded-hal = "0.2.6"

[dependencies.embassy-sync]
version = "0.5.0"
git = "https://github.com/embassy-rs/embassy.git"
rev = "713457ce0087efc2bcf81653feb0f1503c190e53"

[dependencies.embassy-stm32]
version = "0.1.0"
git = "https://github.com/embassy-rs/embassy.git"
rev = "713457ce0087efc2bcf81653feb0f1503c190e53"
features = [
  "unstable-pac",
  "time-driver-any",
  "exti",
  "chrono",
]
optional = true


[dependencies.embassy-executor]
version = "0.4.0"
git = "https://github.com/embassy-rs/embassy.git"
rev = "713457ce0087efc2bcf81653feb0f1503c190e53"
features = ["nightly"]

[dependencies.embassy-time]
version = "0.2.0"
git = "https://github.com/embassy-rs/embassy.git"
rev = "713457ce0087efc2bcf81653feb0f1503c190e53"

[dependencies.embassy-futures]
version = "0.1.0"
git = "https://github.com/embassy-rs/embassy.git"
rev = "713457ce0087efc2bcf81653feb0f1503c190e53"


[features]
default = [
  # "std"
  "f103c8",
  "defmt",
  "memoryx"
]

f407vg = ["stm32", "embassy-stm32/stm32f407vg"]
f103c8 = ["stm32", "embassy-stm32/stm32f103c8"]

stm32 = [
  "embassy-stm32",
  "embassy-executor/executor-thread",
  # "embassy-executor/executor-interrupt",
  "embassy-executor/integrated-timers",
  "embassy-time/tick-hz-32_768",
  "cortex-m",
  "cortex-m-rt",
  "embassy-executor/arch-cortex-m",
]

defmt = [
  "dep:defmt",
  "defmt-rtt",
  "panic-probe",
  "embassy-executor/defmt",
  "embassy-stm32/defmt",
]

std = [
  "embassy-executor/arch-std",
  "embassy-executor/executor-thread",
  "embassy-executor/log",
  "embassy-executor/integrated-timers",
  "embassy-time/log",
  "embassy-time/std",
  "async-io",
  "embedded-io-async/std",
]

memoryx = [
  "embassy-stm32/memory-x",
]

with_bootloader = []

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = true
opt-level = 0           # <-
overflow-checks = true  # <-
lto = false

# [profile.dev.package."embassy-stm32"]
# codegen-units = 1
# debug = 2
# debug-assertions = true # <-
# incremental = true
# opt-level = 0           # <-
# overflow-checks = true  # <-

[profile.dev.package."*"]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = true
opt-level = "z"          # <-
overflow-checks = false  # <-
#
# # cargo build/run --release
# [profile.release]
# codegen-units = 1
# debug = 2
# debug-assertions = false # <-
# incremental = false
# lto = 'fat'
# opt-level = 2            # <-
# overflow-checks = false  # <-
