workspace = { members = [
  "examples/ahrs",
  "examples/serial_manager",
  "examples/simple-tasks",
  "bsp",
  "libraries/scheduler",
  "libraries/serial-manager",
  "libraries/singleton",
  "libraries/singleton/singleton-procmacro",
  "libraries/imu",
  "examples/pwm",
  "libraries/servo-control",
  "examples/sdcard",
  "libraries/logger",
], resolver = "2" }


# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = true
opt-level = 0           # <-
overflow-checks = true  # <-
lto = false

# [profile.dev.package."embassy-stm32"]
# codegen-units = 1
# debug = 2
# debug-assertions = true # <-
# incremental = true
# opt-level = 0           # <-
# overflow-checks = true  # <-

[profile.dev.package."*"]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = true
opt-level = "s"         # <-
overflow-checks = true  # <-
#
# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false # <-
incremental = false
lto = 'fat'
opt-level = 3            # <-
overflow-checks = false  # <-
