[package]
name = "servo-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-sync = {version = "0.5.0"}
heapless = "0.7.16"
